package byow.DungeonMap;

import byow.Core.Engine;
import byow.Core.RandomUtils;
import byow.TileEngine.TERenderer;
import byow.TileEngine.TETile;
import byow.TileEngine.Tileset;
import edu.princeton.cs.introcs.StdDraw;

import java.awt.*;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Point2D;
import java.util.List;
import java.util.*;
import java.util.stream.Collectors;

public class DungeonMap {
    /**
     * The settings of the game
     */
    private final Settings settings;
    /**
     * The random object
     */
    private final Random random;
    /**
     * The generated random rooms whose centers are inside the "center ellipse".
     */
    private RandomRooms randomRooms;
    /**
     * The graph data structure that support Euclidean weighted graph.
     * Stores the graph that generated by the Delaunay triangulation.
     */
    private EuclideanEdgeWeightedGraph graph;
    /**
     * The minimum spanning tree of the graph.
     */
    private EuclideanPrimMST mst;
    /**
     * The main path of the dungeon map. Contains some additional edges other than the minimum spanning tree.
     */
    private List<Line2D> mainPath = new ArrayList<>();
    /**
     * The paths of hallways of the dungeon map. Hallways are either vertical or horizontal.
     */
    private List<Line2D> hallwayPaths = new ArrayList<>();
    /**
     * The rectangles of the hallways.
     */
    private List<Rectangle> hallwayWallVariation = new ArrayList<>();

    public DungeonMap(Settings settings, Long seed) {
        // TODO: Reorganise Classes to different folders.
        this.settings = settings;
        this.random = new Random(seed);
        // Generate the random rooms with the centers inside the ellipse
        this.randomRooms = new RandomRooms(random, getCenterEllipse(), settings);

        // Get the centers of the main rooms
        List<Point2D> mainCenters = getCentersOfRooms(this.randomRooms.getMainRooms());
        // Get the Delaunay triangulation
        Set<Triangle> delaunayTriangles = new Delaunay().bowyerWatson(mainCenters);
        // Get the sides of the Delaunay triangulation
        Set<Triangle.Side> delaunaySides = this.getSides(delaunayTriangles);

        // Create the graph and the minimum spanning tree
        this.graph = new EuclideanEdgeWeightedGraph(new HashSet<Line2D>(delaunaySides), delaunaySides.size());
        this.mst = new EuclideanPrimMST(this.graph);
        // Create the main path
        this.setMainPath(this.mst.sides(), delaunaySides);

        // Show the graph, the minimum spanning tree and the main path.
        showGraph();
        // Create the hallways paths.
        this.hallwayPaths = buildHallwayPaths(this.mainPath);
        // Create the hallway with shape variations.
        this.hallwayWallVariation = getHallwayWallRooms(this.hallwayPaths, this.randomRooms.getSideRooms());
    }

    /**
     * Returns the ellipse that is centered at the center of the canvas.
     *
     * @return the ellipse
     */
    public Ellipse2D.Double getCenterEllipse() {
        // x, y: left upper corner of the ellipse
        return new Ellipse2D.Double(settings.CENTER.x - settings.ELLIPSE_A_DEFAULT / 2,
                settings.CENTER.y - settings.ELLIPSE_B_DEFAULT / 2, settings.ELLIPSE_A_DEFAULT,
                settings.ELLIPSE_B_DEFAULT);
    }

    /**
     * Get the list of centers of a list of rooms.
     *
     * @param rooms a list of rooms
     * @return the list of centers
     */
    public List<Point2D> getCentersOfRooms(List<Rectangle> rooms) {
        return rooms.stream().map(
                r -> (Point2D) new Point2D.Double(r.getCenterX(), r.getCenterY())).collect(
                Collectors.toList());
    }


    /**
     * Convert a list of triangles to a set of sides.
     *
     * @param triangles the list of triangles generated by Delaunay triangulation
     * @return the set of sides
     */
    private Set<Triangle.Side> getSides(Iterable<Triangle> triangles) {
        Set<Triangle.Side> sides = new HashSet<>();
        triangles.forEach(t -> {
            sides.add(new Triangle.Side(t.a, t.b));
            sides.add(new Triangle.Side(t.b, t.c));
            sides.add(new Triangle.Side(t.c, t.a));
        });
        return sides;
    }

    /**
     * Set the main path of the dungeon map.
     * Not only add the minimum spanning tree edges to the main path, but also add several other
     * from the remaining edges.
     *
     * @param mstSides the sides of the minimum spanning tree
     * @param sides    all the sides of the Delaunay triangulation
     */
    private void setMainPath(Set<Triangle.Side> mstSides, Set<Triangle.Side> sides) {
        // Add all the minimum spanning tree sides to the main path
        this.mainPath.addAll(mstSides);

        // Get the remaining sides
        Set<Triangle.Side> remainingSides = new HashSet<>(sides);
        remainingSides.removeAll(mstSides);

        // Add some random edges from the remaining sides to the main path
        this.mainPath.addAll(pickRandomEdges(remainingSides));
    }


    /**
     * Pick some random edges from a set of triangle sides.
     *
     * @param remainingSides the set of triangle sides
     * @return a set of random edges
     */
    private Set<Triangle.Side> pickRandomEdges(Set<Triangle.Side> remainingSides) {
        // Turn the set into an array
        Triangle.Side[] remainingSidesList = remainingSides.toArray(Triangle.Side[]::new);
        // Shuffle the array
        RandomUtils.shuffle(random, remainingSidesList);
        // Pick the first 15% of the array
        int numberAdded = (int) (remainingSidesList.length * 0.15);
        // Return the set of the first 15% of the array
        return new HashSet<>(Arrays.asList(remainingSidesList).subList(0, numberAdded));
    }

    /**
     * Build the hallways of the dungeon map.
     *
     * @param mainPath the main path of the dungeon map
     * @return the list of hallways paths.
     */
    private List<Line2D> buildHallwayPaths(List<Line2D> mainPath) {
        List<Line2D> path = new ArrayList<>();
        for (Line2D line2D : mainPath) {
            path.addAll(generateRightAnglePath(line2D.getP1(), line2D.getP2()));
        }
        return path;
    }

    /**
     * Generate a right angle path between two points.
     *
     * @param start the start point
     * @param end the end point
     * @return the list of lines that form the right angle path
     */
    private List<Line2D> generateRightAnglePath(Point2D start, Point2D end) {
        List<Line2D> path = new ArrayList<>();
        path.add(new Line2D.Double(start, new Point2D.Double(start.getX(), end.getY())));
        path.add(new Line2D.Double(new Point2D.Double(start.getX(), end.getY()), end));

        // Potential improvement: multiple paths instead of two between two points.
        // 1. randomly choose a direction
        // 2. move in that direction with a random distance in range (0, twice the distance to the end)
        return path;
    }

    /**
     * Get the hallway wall rooms.
     * The hallway wall rooms are the side rooms (not main rooms) that intersect with the hallway paths.
     *
     * @param hallways the hallway paths
     * @param sideRooms the side rooms
     * @return the hallway wall rooms
     */
    private List<Rectangle> getHallwayWallRooms(List<Line2D> hallways, List<Rectangle> sideRooms) {
        List<Rectangle> hallwayWallVariation = new ArrayList<>();
        for (Line2D hallway : hallways) {
            for (Rectangle room : sideRooms) {
                if (room.intersectsLine(hallway)) {
                    hallwayWallVariation.add(room);
                }
            }
        }
        return hallwayWallVariation;
    }

    /**
     * Get the 2D TETile representation of the world.
     * The world is represented by a 2D TETile array.
     *
     * @return the 2D TETile representation of the world
     */
    public TETile[][] getWorldFrame() {
        // 1. Initialize the world with NOTHING
        TETile[][] world = new TETile[settings.WIDTH][settings.HEIGHT];
        for (int i = 0; i < settings.HEIGHT; i++) {
            for (int j = 0; j < settings.WIDTH; j++) {
                world[j][i] = Tileset.NOTHING;
            }
        }

        // 2. Create the hallways
        // 2.1 Create the hallway rooms
        for (Rectangle hallwayRoom : hallwayWallVariation) {
            for (int i = hallwayRoom.x; i < hallwayRoom.x + hallwayRoom.width; i++) {
                for (int j = hallwayRoom.y; j < hallwayRoom.y + hallwayRoom.height; j++) {
                    if (i >= 0 && i < settings.WIDTH && j >= 0 && j < settings.HEIGHT) {
                        world[i][j] = getRandomHallwayTile();
                    }
                }
            }
        }

        // 2.2 Create the hallways lines( width = 0.5 or 1)
        for (Line2D hallway : hallwayPaths) {
            int x1 = (int) hallway.getX1();
            int y1 = (int) hallway.getY1();
            int x2 = (int) hallway.getX2();
            int y2 = (int) hallway.getY2();
            if (x1 == x2) {
                for (int i = Math.min(y1, y2); i <= Math.max(y1, y2); i++) {
                    if (x1 >= 0 && x1 < settings.WIDTH && i >= 0 && i < settings.HEIGHT) {
                        world[x1][i] = getRandomHallwayTile();
                    }
                }
            } else if (y1 == y2) {
                for (int i = Math.min(x1, x2); i <= Math.max(x1, x2); i++) {
                    if (i >= 0 && i < settings.WIDTH && y1 >= 0 && y1 < settings.HEIGHT) {
                        world[i][y1] = getRandomHallwayTile();
                    }
                }
            }
        }

        // 3. Create the main rooms. May overwrite the hallways.
        for (Rectangle room : randomRooms.getMainRooms()) {
            for (int i = room.x; i < room.x + room.width; i++) {
                for (int j = room.y; j < room.y + room.height; j++) {
                    if (i >= 0 && i < settings.WIDTH && j >= 0 && j < settings.HEIGHT) {
                        world[i][j] = getRandomRoomTile();
                    }
                }
            }
        }
        
        // 4. Create the walls.
        for (int i = 0; i < settings.WIDTH; i++) {
            for (int j = 0; j < settings.HEIGHT; j++) {
                if (i == 0 || i == settings.WIDTH - 1 || j == 0 || j == settings.HEIGHT - 1) {
                    if (world[i][j] != Tileset.WALL && world[i][j] != Tileset.NOTHING) {
                        world[i][j] = Tileset.WALL;
                    }
                }
                if (world[i][j] == Tileset.NOTHING) {
                    if (i > 0 && world[i - 1][j] != Tileset.NOTHING && world[i - 1][j] != Tileset.WALL) {
                        world[i][j] = Tileset.WALL;
                    } else if (i < settings.WIDTH - 1 && world[i + 1][j] != Tileset.NOTHING && world[i + 1][j] != Tileset.WALL) {
                        world[i][j] = Tileset.WALL;
                    } else if (j > 0 && world[i][j - 1] != Tileset.NOTHING && world[i][j - 1] != Tileset.WALL) {
                        world[i][j] = Tileset.WALL;
                    } else if (j < settings.HEIGHT - 1 && world[i][j + 1] != Tileset.NOTHING && world[i][j + 1] != Tileset.WALL) {
                        world[i][j] = Tileset.WALL;
                    }
                }
            }
            
        }
        return world;
    }

    private TETile getRandomHallwayTile() {
        int tileNum = random.nextInt(11);
        return Tileset.FLOWER;
    }
    private TETile getRandomRoomTile() {
        int tileNum = random.nextInt(11);
        return Tileset.FLOWER;
    }

    /**
     * Show the graph, the minimum spanning tree and the main path.
     * <p>
     * If the env variable DEV_ENV is false, this method won't run and the display of the graph will be skipped.
     */
    public void showGraph() {
        // If the env variable DEV_ENV is false, skip the display of the graph.
        if (!Engine.DEV_ENV) {
            return;
        }
        this.graph.show();
        this.mst.show();
        for (Line2D line : this.mainPath) {
            StdDraw.setPenColor(StdDraw.YELLOW);
            StdDraw.setPenRadius();
            StdDraw.line(line.getX1(), line.getY1(), line.getX2(), line.getY2());
        }
    }

    /**
     * The main method to test the dungeon map.
     * @param args
     */
    public static void main(String[] args) {
        // To show the animation of the generation process, this method should be used instead of
        // the ter.initialize() method. The ter.initialize() method will enable the StdDraw double
        // buffering, which will cause the animation gone.
        GraphUtils.initCanvas(GraphUtils.SETTINGS1);
        GraphUtils.SETTINGS1.SIZE_THRESHOLD = 1.0;
        TERenderer ter = new TERenderer();
        DungeonMap dungeonMap = new DungeonMap(GraphUtils.SETTINGS1, 123L);
        // After the dungeon map is generated, the world frame can be rendered by this method,
        // otherwise the animation will be too slow.
        ter.initialize(GraphUtils.SETTINGS1.WIDTH, GraphUtils.SETTINGS1.HEIGHT);
        ter.renderFrame(dungeonMap.getWorldFrame());
    }
}
